# Generated by Django 5.2.8 on 2025-12-02 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll'),
        ),
        migrations.AddField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option'),
        ),
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['-created_at'], name='polls_poll_created_fdd0dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('poll', 'text')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_id', 'poll'], name='polls_vote_voter_i_f88305_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll'], name='polls_vote_poll_id_cee50f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voter_id')},
        ),
    ]
